version: "3.7"

services:
  web:
    build:
      context: ../
      # Note that this is based on the context dir
      # (Mostly) everything else is based off the
      # compose file's dir
      dockerfile: ./docker/Dockerfile
    command: python3 -u docker/init.py
    volumes:
      - type: bind
        # set the path below to wherever you have cloned this repository.
        source: /home/pi/guyamoe
        target: /guya
    ports:
      - 8000:8000
    environment:
      - PYTHONUNBUFFERED=1
      # Add the IP of the device you're hosting on below. Doing so will add your IP to ALLOWED_HOSTS.
      - HOST_IP=
      - DJANGO_SETTINGS_MODULE=docker.settings
    depends_on:
      - memcached
      - postgres
    networks:
      - guyamoe-intercontinental-highway
  memcached:
    image: memcached:latest
    restart: always
    entrypoint:
      - memcached
      - -m 512
    networks:
      - guyamoe-intercontinental-highway
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
      - POSTGRES_USER=POSTGRES_USER
      - POSTGRES_DB=kaguyamoe
    networks:
      - guyamoe-intercontinental-highway

# Give the network a name so it's more deterministic
# Otherwise it defaults to <directory>_default
networks:
  guyamoe-intercontinental-highway:
    name: guyamoe-intercontinental-highway
